Aru.Web/Aru.Web/ViewModels/NewsViewModel.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Aru.Web.ViewModels
{
    public class NewsViewModel
    {
        [JsonProperty("news_id")]
        public string NewsId { get; set; }
        [JsonProperty("news_title")]
        public string Title { get; set; }
        [JsonProperty("news_desc")]
        public string Desc { get; set; }
        [JsonProperty("news_content")]
        public string Content { get; set; }
        [JsonProperty("news_ispublish")]
        public bool IsPublish { get; set; }
        [JsonProperty("news_publishdate")]
        public DateTime PublishedDate { get; set; }
    }
}

Aru.Web/Aru.Web/Controllers/NewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Aru.Business.Entities;
using Aru.Business.Interfaces;
using Aru.Web.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;
using Radyalabs.Core.Extensions;
using Radyalabs.Core.Helpers;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Aru.Web.Controllers
{
    [Authorize(Roles = "SA")]
    public class NewsController : Controller
    {
        private readonly IContentManagementService newsService;
        public NewsController(IContentManagementService newsService)
        {
            this.newsService = newsService;
        }
        public override void OnActionExecuted(ActionExecutedContext context)
        {
            ViewBag.SelectedMenu = "news";

            base.OnActionExecuted(context);
        }
        public IActionResult Index()
        {
            return View();
        }

        //public IActionResult Details()
        //{
        //    return View();
        //}

        //public IActionResult Create()
        //{
        //    return View();
        //}

        public ActionResult Details(string id)
        {
            var newsDetail = new NewsViewModel();
            var result = newsService.Get(id);
            if (result != null)
                CopyProperty.CopyPropertiesTo(result, newsDetail);

            return View(newsDetail);
        }

        public IActionResult Create()
        {
            NewsViewModel model = new NewsViewModel();

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([FromForm]NewsViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var userAuth = Aru.Web.Helpers.AppCookieHelper.Get<UserAuthenticated>(this.HttpContext);

                    NewsModel news = new NewsModel();
                    CopyProperty.CopyPropertiesTo(model, news);

                    news.NewsId = Guid.NewGuid().ToString();

                    newsService.Add(news, userAuth.UserId, false);

                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {
                    ViewBag.ErrorMessage = ex.Message;
                }
            }

            return View(model);
        }

        [HttpGet]
        public IActionResult Edit(string id)
        {
            NewsViewModel model = new NewsViewModel();

            try
            {
                if (string.IsNullOrEmpty(id))
                    return NotFound();

                var news = newsService.Get(id);
                if (news == null)
                    return NotFound();

                CopyProperty.CopyPropertiesTo(news, model);
            }
            catch (Exception ex)
            {
                return NotFound();
            }

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(string id, NewsViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var userAuth = Aru.Web.Helpers.AppCookieHelper.Get<UserAuthenticated>(this.HttpContext);

                    NewsModel news = new NewsModel();
                    CopyProperty.CopyPropertiesTo(model, news);
                    news.NewsId = id;

                    newsService.Edit(news, userAuth.UserId);
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {
                    ViewBag.ErrorMessage = ex.Message;
                }
            }

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(string id)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var userAuth = Aru.Web.Helpers.AppCookieHelper.Get<UserAuthenticated>(this.HttpContext);
                    newsService.Delete(id, userAuth.UserId);
                }
                catch (Exception ex)
                {
                    ViewBag.ErrorMessage = ex.Message;
                }
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

Aru.Web/Aru.Web/Controllers/SurveyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Aru.Business.Entities;
using Aru.Business.Interfaces;
using Aru.Web.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;
using Radyalabs.Core.Helpers;

namespace Aru.Web.Controllers
{
    [Authorize]
    public class SurveyController : Controller
    {
        private readonly ISurveyService surveyService;
        public SurveyController(ISurveyService surveyService)
        {
            this.surveyService = surveyService;
        }

        public override void OnActionExecuted(ActionExecutedContext context)
        {
            ViewBag.SelectedMenu = "survey";

            base.OnActionExecuted(context);
        }

        // GET: Survey
        public ActionResult Index()
        {
            return View();
        }

        // GET: Survey/Details/5
        public ActionResult Details(string id)
        {
            if (string.IsNullOrEmpty(id))
                return NotFound();

            var result = surveyService.Get(id);
            if (result == null)
                return NotFound();
            
            SurveyViewModel surveyViewModel = new SurveyViewModel();
            CopyProperty.CopyPropertiesTo(result, surveyViewModel);
            surveyViewModel.StartDate.ToLocalTime();
            surveyViewModel.EndDate.ToLocalTime();

            return View(surveyViewModel);
        }

        // GET: Survey/Create
        public ActionResult Create()
        {

            return View();
        }

        // POST: Survey/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(SurveyViewModel collection)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var userAuth = Aru.Web.Helpers.AppCookieHelper.Get<UserAuthenticated>(this.HttpContext);

                    // TODO: Add insert logic here
                    SurveyModel surveyModel = new SurveyModel();

                    CopyProperty.CopyPropertiesTo(collection, surveyModel);
                    surveyModel.SurveyId = Guid.NewGuid().ToString();
                    surveyModel.StartDate = collection.StartDate.ToUniversalTime();
                    surveyModel.EndDate = collection.EndDate.ToUniversalTime();

                    surveyService.Add(surveyModel, userAuth.UserId);
                    return RedirectToAction(nameof(Index));
                }
                catch(Exception ex)
                {
                    ViewBag.ErrorMessage = ex.Message;
                }
            }

            return View(collection);
        }

        // GET: Survey/Edit/5
        public ActionResult Edit(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return NotFound();
            }

            var result = surveyService.Get(id);
            if(result == null)
            {
                return NotFound();
            }

            SurveyViewModel surveyViewModel = new SurveyViewModel();
            CopyProperty.CopyPropertiesTo(result, surveyViewModel);
            surveyViewModel.StartDate.ToLocalTime();
            surveyViewModel.EndDate.ToLocalTime();

            return View(surveyViewModel);
        }

        // POST: Survey/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(string id, SurveyViewModel collection)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var userAuth = Aru.Web.Helpers.AppCookieHelper.Get<UserAuthenticated>(this.HttpContext);

                    // TODO: Add update logic here
                    SurveyModel surveyModel = new SurveyModel();
                    CopyProperty.CopyPropertiesTo(collection, surveyModel);

                    surveyModel.SurveyId = id;
                    surveyModel.StartDate = collection.StartDate.ToUniversalTime();
                    surveyModel.EndDate = collection.EndDate.ToUniversalTime();

                    surveyService.Edit(surveyModel, userAuth.UserId);

                    return RedirectToAction(nameof(Index));
                }
                catch(Exception ex)
                {
                    ViewBag.ErrorMessage = ex.Message;
                }
            }

            return View(collection);
        }
        
        // POST: Survey/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(string id)
        {
            try
            {
                var userAuth = Aru.Web.Helpers.AppCookieHelper.Get<UserAuthenticated>(this.HttpContext);

                surveyService.Delete(id, userAuth.UserId);
            }
            catch(Exception ex)
            {
                TempData["ErrorMessage"] = ex.Message;
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

Aru.Web/Aru.Web/Views/News/Create.cshtml
@model Aru.Web.ViewModels.NewsViewModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section CustomScripts{
    <script type="text/javascript">
        jQuery(document).ready(function () {
            var errorMessage = '@ViewBag.ErrorMessage';
            if (errorMessage != '') {
                $('#errMessageTxt').text(errorMessage);
                $('#failedDialog').modal('show');
            }
        });

        $(function () {
            $('#datetime').datetimepicker();
        });
    </script>
}

<div class="page-content">
    <!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
    <!-- Success Dialog -->
    <div class="modal fade" id="failedDialog" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="pos_middle">
            <div class="modal-dialog modal-sm">
                <div class="modal-content">
                    <div class="modal-body" style="padding: 20px 25px;">
                        <br />
                        <br />
                        <center><i class="fa fa-frown-o fa-8x font-red"></i></center>
                        <h4 class="text-center font-grey-gallery" id="errMessageTxt">
                            Permitaan edit parameter <b>Periode Export - Import</b> telah berhasil di kirim ke Admin Cheker untuk melakukan review dan persetujuan
                        </h4>
                        <br />
                        <a href="#" class="btn btn-padd2 btn-block grey-cascade uppercase no-margin" data-dismiss="modal" aria-hidden="true">Ok</a>
                    </div>
                </div>
                <!-- /.modal-content -->
            </div>
        </div>
        <!-- /.modal-dialog -->
    </div>
    <!-- /.modal -->
    <!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
    <!-- BEGIN PAGE HEADER-->
    <!-- BEGIN PAGE BREADCRUMB -->
    <ul class="page-breadcrumb breadcrumb">
        <li>
            <a href="#">Home</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <a href="#">Manage News</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <a href="#">Add New News</a>
        </li>
    </ul>
    <!-- END PAGE BREADCRUMB -->
    <!-- BEGIN PAGE HEAD -->
    <div class="page-head">
        <!-- BEGIN PAGE TITLE -->
        <div class="page-title">
            <h1>Add New News</h1>
        </div>
        <!-- END PAGE TITLE -->
    </div>
    <!-- END PAGE HEAD -->
    <!-- END PAGE HEADER-->
    <!-- BEGIN PAGE CONTENT-->
    <div class="row">
        <div class="col-md-12">
            <div class="portlet light bordered">
                <div class="portlet-body form">
                    <form asp-action="create" class="form-horizontal form-row-seperated">
                        <div class="form-body">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <div class="form-group">
                                <label asp-for="Title" class="control-label col-md-3"></label>
                                <div class="col-md-5">
                                    <input asp-for="Title" class="form-control" />
                                    <span asp-validation-for="Title" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="form-group">
                                <label asp-for="PublishedDate" class="control-label col-md-3"></label>
                                <div class="col-md-5">
                                    <input asp-for="PublishedDate" type="date" class="form-control" />
                                    <span asp-validation-for="PublishedDate" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="form-group">
                                <label asp-for="Desc" class="control-label col-md-3"></label>
                                <div class="col-md-5">
                                    <input asp-for="Desc" type="text" class="form-control" />
                                    <span asp-validation-for="Desc" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="form-group">
                                <label asp-for="Content" class="control-label col-md-3"></label>
                                <div class="col-md-5">
                                    <textarea asp-for="Content" type="text" class="form-control" ></textarea>
                                    <span asp-validation-for="Content" class="text-danger"></span>
                                </div>
                            </div>
                            @*<div class="form-group">
                                <label asp-for="IsPublish" class="control-label col-md-3"></label>
                                <div class="col-md-5">
                                    <input asp-for="IsPublish" type="checkbox" class="form-control" />
                                    <span asp-validation-for="IsPublish" class="text-danger"></span>
                                </div>
                            </div>*@

                            <div class="form-group">
                                <label asp-for="IsPublish" class="control-label col-md-3"></label>
                                <div class="col-md-5">
                                    <div class="checkbox">
                                        <input asp-for="IsPublish" class="form-control" />
                                    </div>
                                </div>
                            </div>
                        </div>
                        <br />
                        <div class="form-actions">
                            <div class="row">
                                <div class="col-md-offset-3 col-md-9">
                                    <a class="btn btn-padd2 grey-cascade" asp-action="index">Cancel</a>
                                    <button type="submit" class="btn btn-padd2 green" style="margin-left: 10px;">Submit</button>
                                </div>
                            </div>
                        </div>
                    </form>
                    <!-- END FORM-->
                </div>
            </div>
        </div>
    </div>
    <!-- END PAGE CONTENT-->
</div>

Aru.Web/Aru.Web/Views/News/Details.cshtml
@model Aru.Web.ViewModels.NewsViewModel
@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<form asp-action="delete">
    <div class="modal fade" id="confirmDelete" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="pos_middle">
            <div class="modal-dialog modal-sm">
                <div class="modal-content">
                    <div class="modal-body" style="padding: 20px 25px;">
                        <h4 class="text-center font-grey-gallery" style="font-weight: 600;">Are you sure to delete this ?</h4>
                        <br />
                        <input type="hidden" value="@Model.NewsId" name="id" />
                        <div class="row">
                            <div class="col-md-6">
                                <button type="submit" class="btn btn-block green uppercase" data-backdrop="static" data-keyboard="false">Yes</button>
                            </div>
                            <div class="col-md-6">
                                <a href="#" class="btn btn-block red uppercase" data-backdrop="static" data-keyboard="false" data-dismiss="modal">No</a>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /.modal-content -->
            </div>
        </div>
        <!-- /.modal-dialog -->
    </div>
</form>
<div class="page-content">
    <!-- BEGIN PAGE HEADER-->
    <!-- BEGIN PAGE HEAD -->
    
    
    <!-- END PAGE HEAD -->
    <!-- BEGIN PAGE BREADCRUMB -->
    <ul class="page-breadcrumb breadcrumb">
        <li>
            <a asp-action="Index">Manage News</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <a asp-controller="Survey" asp-action="Details" asp-route-id=""></a>
        </li>
    </ul>
    <!-- END PAGE BREADCRUMB -->
    <!-- BEGIN PAGE TITLE -->
    <div class="page-head">
        <div class="page-title">
            <h1>Detail News</h1>
        </div>
    </div>
        <!-- END PAGE TITLE -->
        <!-- END PAGE HEADER-->
        <!-- BEGIN PAGE CONTENT-->
        <div class="row">
            <div class="col-md-12">
                <div class="portlet light bordered">
                    @*<div class="portlet-title">
                        <div class="caption">
                            <span class="caption-subject bold ">News</span>
                        </div>
                    </div>*@
                    <div class="row">
                        <div class="col-md-12">
                            <div class="content-detail">
                                <!-- Data User -->
                                <div class="portlet light bordered">
                                    <div class="portlet-title  text-right">
                                        <!-- ACTION BUTTON-->
                                        <div class="caption col-md-12">
                                            <div class="row">
                                                <div class="col-md-12">
                                                    <a class="btn btn-padd2 red" data-backdrop="static" data-keyboard="false" data-dismiss="modal" data-toggle="modal" data-target="#confirmDelete" href="#confirmDelete"><i class="fa fa-trash-o" aria-hidden="true"></i></a>
                                                    <a class="btn btn-padd2 green" asp-action="edit" asp-controller="news" asp-route-id="@Model.NewsId"><i class="fa fa-pencil" aria-hidden="true"></i></a>
                                                </div>
                                            </div>
                                        </div>
                                        <!--END ACTION BUTTON-->
                                    </div>
                                    <div class="portlet-body form">
                                        <!-- BEGIN FORM-->
                                        <form action="#" class="form-horizontal">
                                            <div class="portlet-body form">
                                                <div class="form-horizontal form-row-seperated">
                                                    <div class="form-body">
                                                        <div class="form-group">
                                                            <label class="control-label col-md-3">Name</label>
                                                            <div class="col-md-5">
                                                                <label class="control-label" style="color:black;">@Html.DisplayFor(model => model.Title)</label>
                                                                <span class="text-danger"></span>
                                                            </div>
                                                        </div>
                                                        <div class="form-group">
                                                            <label class="control-label col-md-3">Published Date</label>
                                                            <div class="col-md-5">
                                                                <label class="control-label" style="color:black;">@Html.DisplayFor(model => model.PublishedDate)</label>
                                                                <span class="text-danger"></span>
                                                            </div>
                                                        </div>
                                                        <div class="form-group">
                                                            <label class="control-label col-md-3">Description</label>
                                                            <div class="col-md-5">
                                                                <label class="control-label" style="color:black;">@Html.DisplayFor(model => model.Desc)</label>
                                                                <span class="text-danger"></span>
                                                            </div>
                                                        </div>
                                                        <div class="form-group">
                                                            <label class="control-label col-md-3">Content</label>
                                                            <div class="col-md-5">
                                                                <label class="control-label" style="color:black;">@Html.DisplayFor(model => model.Content)</label>
                                                                <span class="text-danger"></span>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="form-actions text-right">
                                                <div class="row">
                                                    <div class="col-md-offset-3 col-md-9">
                                                        <a class="btn btn-padd2 grey-cascade" asp-action="index">Back</a>
                                                    </div>
                                                </div>
                                            </div>
                                        </form>
                                        <!-- END FORM-->
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div>
                    </div>
                </div>
            </div>
        </div>
        <!-- END PAGE CONTENT-->
    </div>

Aru.Web/Aru.Web/Views/News/Edit.cshtml
@model Aru.Web.ViewModels.NewsViewModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section CustomScripts{
    <script type="text/javascript">
        jQuery(document).ready(function () {
            var errorMessage = '@ViewBag.ErrorMessage';
            if (errorMessage != '') {
                $('#errMessageTxt').text(errorMessage);
                $('#failedDialog').modal('show');
            }
        });
    </script>
}

<div class="page-content">
    <!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
    <!-- Success Dialog -->
    <div class="modal fade" id="failedDialog" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="pos_middle">
            <div class="modal-dialog modal-sm">
                <div class="modal-content">
                    <div class="modal-body" style="padding: 20px 25px;">
                        <br />
                        <br />
                        <center><i class="fa fa-frown-o fa-8x font-red"></i></center>
                        <h4 class="text-center font-grey-gallery" id="errMessageTxt">
                            Permitaan edit parameter <b>Periode Export - Import</b> telah berhasil di kirim ke Admin Cheker untuk melakukan review dan persetujuan
                        </h4>
                        <br />
                        <a href="#" class="btn btn-padd2 btn-block grey-cascade uppercase no-margin" data-dismiss="modal" aria-hidden="true">Ok</a>
                    </div>
                </div>
                <!-- /.modal-content -->
            </div>
        </div>
        <!-- /.modal-dialog -->
    </div>
    <!-- /.modal -->
    <!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
    <!-- BEGIN PAGE HEADER-->
    <!-- BEGIN PAGE BREADCRUMB -->
    <ul class="page-breadcrumb breadcrumb">
        <li>
            <a href="#">Home</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <a href="#">Manage News</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <a href="#">Add New News</a>
        </li>
    </ul>
    <!-- END PAGE BREADCRUMB -->
    <!-- BEGIN PAGE HEAD -->
    <div class="page-head">
        <!-- BEGIN PAGE TITLE -->
        <div class="page-title">
            <h1>Add New News</h1>
        </div>
        <!-- END PAGE TITLE -->
    </div>
    <!-- END PAGE HEAD -->
    <!-- END PAGE HEADER-->
    <!-- BEGIN PAGE CONTENT-->
    <div class="row">
        <div class="col-md-12">
            <div class="portlet light bordered">
                <div class="portlet-body form">
                    <form asp-action="edit" class="form-horizontal form-row-seperated">
                        <div class="form-body">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <div class="form-group">
                                <label asp-for="Title" class="control-label col-md-3"></label>
                                <div class="col-md-5">
                                    <input asp-for="Title" class="form-control" />
                                    <span asp-validation-for="Title" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="form-group">
                                <label asp-for="PublishedDate" class="control-label col-md-3"></label>
                                <div class="col-md-5">
                                    <input asp-for="PublishedDate" type="date" class="form-control" />
                                    <span asp-validation-for="PublishedDate" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="form-group">
                                <label asp-for="Desc" class="control-label col-md-3"></label>
                                <div class="col-md-5">
                                    <input asp-for="Desc" type="text" class="form-control" />
                                    <span asp-validation-for="Desc" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="form-group">
                                <label asp-for="Content" class="control-label col-md-3"></label>
                                <div class="col-md-5">
                                    <input asp-for="Content" type="text" class="form-control" />
                                    <span asp-validation-for="Content" class="text-danger"></span>
                                </div>
                            </div>
                            @*<div class="form-group">
                                <label asp-for="IsPublish" class="control-label col-md-3"></label>
                                <div class="col-md-5">
                                    <input asp-for="IsPublish" type="checkbox" class="form-control" />
                                    <span asp-validation-for="IsPublish" class="text-danger"></span>
                                </div>
                            </div>*@

                            <div class="form-group">
                                <label asp-for="IsPublish" class="control-label col-md-3"></label>
                                <div class="col-md-5">
                                    <div class="checkbox">
                                        <input asp-for="IsPublish" class="form-control" />
                                    </div>
                                </div>
                            </div>
                        </div>
                        <br />
                        <div class="form-actions">
                            <div class="row">
                                <div class="col-md-offset-3 col-md-9">
                                    <a class="btn btn-padd2 grey-cascade" asp-action="index">Cancel</a>
                                    <button type="submit" class="btn btn-padd2 green" style="margin-left: 10px;">Submit</button>
                                </div>
                            </div>
                        </div>
                    </form>
                    <!-- END FORM-->
                </div>
            </div>
        </div>
    </div>
    <!-- END PAGE CONTENT-->
</div>